import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn } from 'typeorm';

export enum AnomalySeverity {
  Low = 'Low',
  Medium = 'Medium',
  High = 'High',
  Critical = 'Critical',
}

/**
 * Persisted anomaly flags generated by the AnomalyService.
 * These are advisory findings for PRAZ/PMU review, not automatic sanctions.
 */
@Entity('anomaly_flags')
export class AnomalyFlag {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column()
  type!: string;

  @Column({ type: 'text' })
  description!: string;

  @Column({ type: 'enum', enum: AnomalySeverity })
  severity!: AnomalySeverity;

  @Column({ nullable: true })
  targetType!: string | null;

  @Column({ nullable: true })
  targetId!: string | null;

  @Column({ nullable: true })
  actorId!: string | null;

  @Column({ type: 'jsonb', nullable: true })
  evidence!: any;

  @Column({ default: false })
  reviewed!: boolean;

  @Column({ nullable: true })
  scanRunId!: string | null;

  @CreateDateColumn()
  createdAt!: Date;
}
